#!/bin/sh
REPOSITORY=ssh://v@192.168.1.138:443/home/v/Downloads/Backup/V/v.attic
# Backup all of /home and /var/www except a few
# excluded directories
attic create --stats                            \
    $REPOSITORY::v-`date +%Y-%m-%d`      \
    / 		                            \
    --exclude /home/v/steam        		\
    --exclude /home/v/.local    		\
    --exclude /home/v/vmware			\
    --exclude /proc						\
    --exclude /sys						\
    --exclude /tmp						\
    --exclude /mnt						\
    --exclude /home/v/.armory/ 			\
    --exclude /home/v/.attic/ 			\
    --exclude /home/v/.bitcoin/ 		\
    --exclude /home/v/.bundle/ 			\
    --exclude /home/v/.ccache/ 			\
    --exclude /home/v/.gem/ 			\
    --exclude /home/v/.local/ 			\
    --exclude /home/v/.mozilla/ 		\
    --exclude /home/v/.pki/ 			\
    --exclude /home/v/.sgminer/ 		\
    --exclude /home/v/.thumbnails/ 		\
    --exclude /home/v/.vnc/ 			\
    --exclude /home/v/.wicd/ 			\
    --exclude /home/v/.zcompcache		\
	--exclude /run						\
	--exclude /keybase


# Use the `prune` subcommand to maintain 7 daily, 4 weekly
# and 6 monthly archives.
attic prune -v $REPOSITORY --keep-daily=7 --keep-weekly=4 --keep-monthly=6
