#!/bin/sh
REPOSITORY=ssh://v@192.168.254.23:80/ftp/backup.attic
# Backup all of /home and /var/www except a few
# excluded directories
attic create --stats                            \
    $REPOSITORY::hostname-`date +%Y-%m-%d`      \
    /home/v                                       \
    --exclude /home/v/steam            \
    --exclude /home/v/.local    \
    --exclude /home/v/vmware

# Use the `prune` subcommand to maintain 7 daily, 4 weekly
# and 6 monthly archives.
attic prune -v $REPOSITORY --keep-daily=7 --keep-weekly=4 --keep-monthly=6
