#!/bin/sh
REPOSITORY=ssh://nopriv@veil.my.to:45/home/nopriv/Downloads/Backup/V/v.borg
# Backup all of /home and /var/www except a few
# excluded directories
borg create --stats -C lzma	            		\
    $REPOSITORY::v-`date +%Y-%m-%d_%H:%M`  		\
    /home/v/	                    	    	\
	--exclude /home/v/steam       				\
	--exclude /home/v/ownCloud					\
	--exclude /home/v/Downloads/ownCloud 		\
	--exclude '/home/v/VirtualBox VMs' 			\
    --exclude /home/v/.local	   				\
    --exclude /home/v/vmware					\
    --exclude /home/v/.armory 					\
    --exclude /home/v/.attic 					\
    --exclude /home/v/.bitcoin	 				\
    --exclude /home/v/.bundle 					\
    --exclude /home/v/.ccache 					\
	--exclude /home/v/.cache 					\
	--exclude /home/v/.wine						\
    --exclude /home/v/.gem 						\
    --exclude /home/v/.local 					\
	--exclude /home/v/.local					\
    --exclude /home/v/.mozilla	 				\
    --exclude /home/v/.pki	 					\
    --exclude /home/v/.sgminer					\
    --exclude /home/v/.thumbnails 				\
    --exclude /home/v/.vnc	 					\
    --exclude /home/v/.wicd 					\
    --exclude /home/v/.zcompcache				\
	--exclude /home/v/.config/wine 				\
	--exclude /home/v/.mail 					\
	--exclude /home/v/Music						\
	--exclude /home/v/Downloads/youtube 		\
	--exclude /home/v/Downloads/metasploitable3 \
	--exclude /home/v/Downloads/justseedit 		\
	--exclude '/home/v/My Web Sites'			\
	--exclude /home/v/Downloads/DwarfFortress	\
	--exclude /home/v/Videos					\
	--exclude /home/v/Mail						\
	--exclude /home/v/Git 						\
	--exclude /home/v/Downloads/Movies 			\
	--exclude /home/v/Downloads/VMs

# Use the `prune` subcommand to maintain 7 daily, 4 weekly
# and 6 monthly archives.
borg prune -v $REPOSITORY --keep-within=1y --keep-hourly=336 --keep-daily=7 --keep-weekly=4 --keep-monthly=1 -s
