#! /bin/bash

echo "How much was your check?"
read input

bc <<< $input-10 > .income

income=`cat .income`

bc <<< $input*0.1 > .tithe
bc <<< $income*0.09 > .retire
bc <<< "`cat .income`-(`cat .tithe`+`cat .retire`)" > .savings

tithe=`cat .tithe`

retire=`cat .retire`

savings=`cat .savings`

echo "Your income is $income" 
echo "Your tithe is $tithe"
echo "Your retirement is $retire"
echo "Your savings is $savings"

rm .income
rm .tithe
rm .retire
rm .savings
