#! /bin/bash

echo "How much was your check?"
read -r input

bc <<< "$input-10" > "$HOME/.income"

income="$(cat '$HOME/.income')"

bc <<< "$input*0.1" > "$HOME/.tithe"
bc <<< "$income*0.09" > "$HOME/.retire"
bc <<< "`cat .income`-(`cat .tithe`+`cat .retire`)" > .savings

tithe="$(cat $HOME/.tithe)"

retire=`cat $HOME/.retire`

savings=`cat $HOME/.savings`

echo "Your income is $income" 
echo "Your tithe is $tithe"
echo "Your retirement is $retire"
echo "Your savings is $savings"

rm $HOME/.income
rm $HOME/.tithe
rm $HOME/.retire
rm $HOME/.savings
