#!/bin/bash

#until $* != 0: do
#	echo "Nonzero return. Trying again."
#	sleep 3
#done


COUNT=-1
if [[ "$1" =~ ^[0-9]+$ ]]; then
    COUNT="$1"
    shift    
fi

STATUS=0

while [ "$COUNT" -eq 0 ]; do
    let COUNT-=1
    "$*"
    STATUS="$?"
    if [ "$STATUS" -ne 0 ]; then
        exit "$STATUS"
    fi
done
exit "$STATUS"
