#!/bin/bash
if [ -s $1 ] ; then
    vim $1
    cp $1 /home/v/ownCloud/IT214
	clear
	javac $1
else
    echo "// Written by Joshua Jordi" > $1
	echo "import java.util.*;" >> $1
	echo "import java.io.*;" >> $1
    echo "" >> $1
    echo "public class ${1:0:${#1}-5}" >> $1
    echo "{" >> $1
    echo "  public static void main(String[] args)" >> $1
    echo "  {" >> $1
    echo "    " >> $1
    echo "    " >> $1
    echo "    " >> $1
	echo "  }" >> $1
	echo "}" >> $1
	vim $1
    cp $1 /home/v/ownCloud/IT214
	clear
	javac $1
fi
